name = "Sodium"
uuid = "4f5b5e99-b0ad-42cd-b47a-334e172ec8bd"
authors = ["Gnimuc <qiyupei@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
