name = "Sodium"
uuid = "4f5b5e99-b0ad-42cd-b47a-334e172ec8bd"
authors = ["Gnimuc <qiyupei@gmail.com>"]
version = "1.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
libsodium_jll = "a9144af2-ca23-56d9-984f-0d03f7b5ccf8"

[compat]
julia = "1.3"
libsodium_jll = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
